#!/bin/bash

set -e -u -x

apt update && apt -y install curl
curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh 
chmod +x Miniconda3-latest-Linux-x86_64.sh 
./Miniconda3-latest-Linux-x86_64.sh -b
export PATH=/home/travis/miniconda3/bin:$PATH
conda install conda-build
conda skeleton pypi --manual-url https://github.com/qiime2/qiime2/releases/tag/2017.2.0
