#!/bin/bash

set -e -u -x

curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > miniconda.sh
chmod +x miniconda.sh
./miniconda.sh -b
export PATH=/home/travis/miniconda3/bin:$PATH
conda install conda-build --yes
conda skeleton pypi --manual-url https://github.com/qiime2/qiime2/archive/2017.2.0.zip
cd qiime2
conda build . -c qiime2 --python 3.5 --output-folder ../
cd -
echo "It worked!"
