#!/bin/bash

set -e -u -x

apt update && apt install -y curl
curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh 
chmod +x Miniconda3-latest-Linux-x86_64.sh 
./Miniconda3-latest-Linux-x86_64.sh -b
export PATH=/root/miniconda3/bin:$PATH
conda install conda-build --yes
conda skeleton pypi --manual-url https://github.com/qiime2/qiime2/archive/2017.2.0.zip 
cd qiime2
conda build . -c qiime2 --python 3.5 --output-folder ../
cd -
echo "DONE!"
